jwt:
  secret: ${JWT_SECRET}

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: community
            uri: http://kcsat-spring-community:8080
            predicates:
              - Path=/api/community/**
          - id: question
            uri: http://kcsat-spring-question:8080
            predicates:
              - Path=/api/question/**
  data:
    redis:
      host: ${REDIS_DATASOURCE_HOST}
      port: 6379